### ISSUE TITLE
Session Dashboard

### ISSUE THREAD

**Issue by VoxelPenguin** [c-o-l-i-n/joshies#23]
Currently, the UI is built to be compatible with mobile devices.  For presentation purposes, it would be nice to have a session dashboard to show a summary of statistics and game state on a larger screen such as a TV.  Some potential items to include on the dashboard would be:

### Rankings Table
This one is self-explanatory--just a list of each player's points and ranking.

### Current Round/Phase and Next Round/Phase
This would be the same as what is shown on the mobile homepage, the current round/phase with event info, and the next round/phase with event info.

### Point Value Graph
A graph showing each player's points over time, same as the one shown on the analytics page.

### Bet Ticker
A running ticker showing active bets, similar to a stock market ticker.

### Superlatives
A "slideshow" of player superlatives.  An superlative would be the EMP equivalent of bonus stars in Mario Party.  Examples could be:

> **Feelin' Blue**: `Buddy` has landed on the most blue spaces.
> **Degenerate**: `Tyler` has lost the most points gambling.
>  **Alcoholic**: `Tim` has taken the most shots to avoid losing points.

This would require some sort of infrastructure to track superlatives, which could be useful for assigning some random "bonus stars" at the end of the session.

**Comment by c-o-l-i-n** [comment]
Some duel stats might be fun. Something like "latest duels," or a ticker/slideshow of each player's duel stats (like on the `/analytics/player-duel-stats` page).

Also, bank balance, like on the home page.
