### ISSUE TITLE
Ticker does full refresh when there are 5 open bets

### ISSUE THREAD

**Issue by SimBuckeye** [c-o-l-i-n/joshies#56]
When there are 5 open betters (i.e. the ticker is full), the dashboard ticker does a full "reset" every couple of seconds when it could just stay still.

**Comment by VoxelPenguin** [comment]
Fixed by increasing the "numVisible" property of the carousel to be one more than it normally is when the number of active bets equals the usual numVisible.

`[numVisible]="vm.activeBets.length === visibleBets ? visibleBets + 1: visibleBets"`
